name: Agência Sumô
description: Portfólio do designer Wagner Beethoven!

image-default: "img/image-default.jpg"

url: ""
baseurl: ""
permalink:  /:categories/:title.html

sass:
  sass_dir: scss
  style: compressed