name: Agência Sumô
description: "Portfólio de Wagner Beethoven, Designer experiência na concepção e criação de artefatos digitas e entusiasta da acessibilidade e tecnologia assistivas"
slogan: Portfólio do designer Wagner Beethoven!
image-default: "img/image-default.jpg"

url: ""
baseurl: ""
permalink:  /:categories/:title.html

sass:
  sass_dir: scss
  style: compressed


about-title: UX/UI Designer
about-email: agenciasumo@gmail.com
about-phone: +55 81 986 496 080
about-neighborhood: Jardim Atlântico
about-city: Olinda
about-state: Pernambuco
