name: Agência Sumô
description: Portfólio do designer Wagner Beethoven!
google_analytics:
url: ""
baseurl: ""
permalink:  /:categories/:title.html
image-default: "img/image-default.jpg"
plugins:
  - jekyll-seo-tag