name: Agência Sumô
description: "Portfólio de Wagner Beethoven, designer com experiência na concepção, criação de artefatos digitas, entusiasta da acessibilidade e tecnologia assistivas"
slogan: Portfólio do designer Wagner Beethoven!
image-default: "img/image-default.jpg"


url: "http://sumo.pe"
# baseurl: "/"
permalink: /:categories/:title.html

sass:
  style: compressed

about-name: Wagner Beethoven
about-title: UX/UI Designer
about-email: wagnerbeethoven@gmail.com
about-phone: +55 81 986 496 080
about-neighborhood: Jardim Atlântico
about-city: Olinda
about-state: Pernambuco


compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  blanklines: false
  ignore:
    envs: []

plugins:
  - jekyll-feed
